import type { CalendarEntry } from '../types'
import { generateWeekEntries, getWeekStart, type ScheduleTemplate } from '../data/schedule'

function toDateStr(date: Date): string {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

export function getWeekDates(weekStart: Date): Date[] {
  return Array.from({ length: 7 }, (_, i) => {
    const d = new Date(weekStart)
    d.setDate(d.getDate() + i)
    return d
  })
}

/**
 * Ensures the week containing `anchor` has seeded schedule entries.
 * If no entries exist for any date in that week, the recurring template
 * (Twitch Tue/Thu/Sun, daily TikTok/clips, weekly YouTube, etc.) is
 * generated and appended. User edits/additions made afterward persist
 * independently since they live in the same flat array.
 */
export function ensureWeekSeeded(all: CalendarEntry[], anchor: Date, templates?: ScheduleTemplate[]): CalendarEntry[] {
  const weekStart = getWeekStart(anchor)
  const weekDateStrs = getWeekDates(weekStart).map(toDateStr)
  const hasAny = all.some((e) => weekDateStrs.includes(e.date))
  if (hasAny) return all
  return [...all, ...generateWeekEntries(anchor, templates)]
}

export function entriesForDate(all: CalendarEntry[], dateStr: string): CalendarEntry[] {
  return all.filter((e) => e.date === dateStr).sort((a, b) => a.time.localeCompare(b.time))
}

// CalendarEntry.time is stored as 24h "HH:MM" (sorts correctly as a plain
// string, and matches the native <input type="time"> format) — this is
// purely for display.
export function formatTime12h(time24: string): string {
  const [hStr, mStr] = time24.split(':')
  const h = Number(hStr)
  const period = h >= 12 ? 'PM' : 'AM'
  const h12 = h % 12 === 0 ? 12 : h % 12
  return `${h12}:${mStr} ${period}`
}

// Removes every entry on a single date — used by the Calendar page's
// per-day clear action. No "protect real activity" guardrail here, unlike
// resetWeeksToDefault: this is an explicit, single-day action the user is
// looking directly at, backed by its own confirm step in the UI.
export function clearDay(all: CalendarEntry[], dateStr: string): CalendarEntry[] {
  return all.filter((e) => e.date !== dateStr)
}

// Removes every entry in the Sun-Sat week containing `anchor`.
export function clearWeek(all: CalendarEntry[], anchor: Date): CalendarEntry[] {
  const weekDateStrs = new Set(getWeekDates(getWeekStart(anchor)).map(toDateStr))
  return all.filter((e) => !weekDateStrs.has(e.date))
}

// Parses a "YYYY-MM-DD" CalendarEntry.date as a local date. `new Date(str)`
// parses date-only strings as UTC midnight, which can land on the wrong
// local day near a timezone boundary — this avoids that.
function parseDateStr(dateStr: string): Date {
  const [y, m, d] = dateStr.split('-').map(Number)
  return new Date(y, m - 1, d)
}

export interface ResetSummary {
  weeksReset: number
  weeksProtected: number
}

// Regenerates every week's entries from the current recurring schedule so
// they pick up template edits (new times/pillars/titles) — except the week
// containing `keepDate` (left untouched entirely) and any week with real
// activity: a status other than "planned", or an entry that wasn't
// auto-generated by the schedule (added manually or via Fill Week). Those
// are always left alone, so this can never wipe out something you actually
// did or planned by hand.
export function resetWeeksToDefault(
  all: CalendarEntry[],
  keepDate: Date,
  templates: ScheduleTemplate[],
): { entries: CalendarEntry[]; summary: ResetSummary } {
  const keepWeekStr = toDateStr(getWeekStart(keepDate))

  const byWeek = new Map<string, CalendarEntry[]>()
  for (const e of all) {
    const weekStr = toDateStr(getWeekStart(parseDateStr(e.date)))
    if (!byWeek.has(weekStr)) byWeek.set(weekStr, [])
    byWeek.get(weekStr)!.push(e)
  }

  let weeksReset = 0
  let weeksProtected = 0
  let result: CalendarEntry[] = []

  for (const [weekStr, weekEntries] of byWeek) {
    if (weekStr === keepWeekStr) {
      result = result.concat(weekEntries)
      continue
    }
    const isUntouched = weekEntries.every((e) => e.status === 'planned' && e.id.startsWith('seed-'))
    if (!isUntouched) {
      weeksProtected += 1
      result = result.concat(weekEntries)
      continue
    }
    weeksReset += 1
    result = result.concat(generateWeekEntries(parseDateStr(weekStr), templates))
  }

  return { entries: result, summary: { weeksReset, weeksProtected } }
}

export { toDateStr }
